// ticketsTypes.js
export const FETCH_TICKETS_REQUEST = 'FETCH_TICKETS_REQUEST';
export const FETCH_TICKETS_SUCCESS = 'FETCH_TICKETS_SUCCESS';
export const FETCH_TICKETS_FAILURE = 'FETCH_TICKETS_FAILURE';
export const FETCH_APPEND_TICKETS_SUCCESS = 'FETCH_APPEND_TICKETS_SUCCESS';
export const SET_TICKETS = 'SET_TICKETS';
